In [63]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [64]:
df = sns.load_dataset('tips')

In [65]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [66]:
df.shape

(244, 7)

In [67]:
# Predict what is the time ? if anyone is visiting is it lunnch or dinner >> time is the target variable

In [68]:
df.time.unique()

['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

In [69]:
# EDA >> subjective

# encoding, missing value treatment, scaling >> automate these things

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [71]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [72]:
# still we will see the null value imputation as well

In [73]:
# since time is a nominal variable then we will use label encoding

In [74]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [75]:
df['time'] = encoder.fit_transform(df['time'])

In [76]:
df['time']

0      0
1      0
2      0
3      0
4      0
      ..
239    0
240    0
241    0
242    0
243    0
Name: time, Length: 244, dtype: int64

In [77]:
df['time'].unique()

array([0, 1])

In [78]:
# dinner - 1, lunch - 0

In [79]:
X = df.drop('time', axis = 1)
y = df['time']

In [80]:
X

total_bill   tip     sex smoker   day  size
0         16.99  1.01  Female     No   Sun     2
1         10.34  1.66    Male     No   Sun     3
2         21.01  3.50    Male     No   Sun     3
3         23.68  3.31    Male     No   Sun     2
4         24.59  3.61  Female     No   Sun     4
..          ...   ...     ...    ...   ...   ...
239       29.03  5.92    Male     No   Sat     3
240       27.18  2.00  Female    Yes   Sat     2
241       22.67  2.00    Male    Yes   Sat     2
242       17.82  1.75    Male     No   Sat     2
243       18.78  3.00  Female     No  Thur     2

[244 rows x 6 columns]

In [81]:
y

0      0
1      0
2      0
3      0
4      0
      ..
239    0
240    0
241    0
242    0
243    0
Name: time, Length: 244, dtype: int64

In [82]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 1)

In [83]:
X_train.head()

total_bill   tip     sex smoker  day  size
0         16.99  1.01  Female     No  Sun     2
154       19.77  2.00    Male     No  Sun     4
167       31.71  4.50    Male     No  Sun     4
110       14.00  3.00    Male     No  Sat     2
225       16.27  2.50  Female    Yes  Fri     2

In [84]:
X_test.head()

total_bill   tip     sex smoker   day  size
67         3.07  1.00  Female    Yes   Sat     1
243       18.78  3.00  Female     No  Thur     2
206       26.59  3.41    Male    Yes   Sat     3
122       14.26  2.50    Male     No  Thur     2
89        21.16  3.00    Male     No  Thur     2

In [85]:
# handling the missing value
# data encoding
# feature scaling

In [86]:
from sklearn.impute import SimpleImputer # for missing value
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

from sklearn.pipeline import Pipeline # a sequence of data transfomer
from sklearn.compose import ColumnTransformer # Groups all the pipeline steps for each of the columns

In [87]:
df.sample(1)

total_bill   tip     sex smoker  day  time  size
37       16.93  3.07  Female     No  Sat     0     3

In [88]:
cat_cols = ["sex", "smoker", "day"]
num_cols = ["total_bill", "tip", "size"]

In [89]:
# we have to creat differnt pipelines
# feature engineering automation using pipeline and columsn transoformer

In [90]:
num_pipeline = Pipeline(steps = [('imputation', SimpleImputer(strategy='median')),
                  ('scaling', StandardScaler())])

In [91]:
cat_pipeline = Pipeline(steps = [('imputation', SimpleImputer(strategy='most_frequent')),
                  ('encoding', OneHotEncoder())] )

In [92]:
preprocessor = ColumnTransformer([("num_pipeline", num_pipeline, num_cols),
("cat_pipeline", cat_pipeline, cat_cols)])

In [93]:
preprocessor

ColumnTransformer(transformers=[('num_pipeline',
                                 Pipeline(steps=[('imputation',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaling',
                                                  StandardScaler())]),
                                 ['total_bill', 'tip', 'size']),
                                ('cat_pipeline',
                                 Pipeline(steps=[('imputation',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoding',
                                                  OneHotEncoder())]),
                                 ['sex', 'smoker', 'day'])])

In [94]:
X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)

In [95]:
X_train

array([[-0.28611937, -1.47443803, -0.57766863, ...,  0.        ,
         1.        ,  0.        ],
       [ 0.02695905, -0.71612531,  1.47042924, ...,  0.        ,
         1.        ,  0.        ],
       [ 1.3716196 ,  1.19880579,  1.47042924, ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [-0.23206267,  0.43283335, -0.57766863, ...,  0.        ,
         0.        ,  1.        ],
       [-1.06543688, -1.29060464, -0.57766863, ...,  1.        ,
         0.        ,  0.        ],
       [-0.29287646,  0.1034652 ,  0.44638031, ...,  1.        ,
         0.        ,  0.        ]])

In [96]:
X_test

array([[-1.85376383, -1.48209775, -1.60171757,  1.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [-0.08453291,  0.04984713, -0.57766863,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [ 0.79501474,  0.36389583,  0.44638031,  0.        ,  1.        ,
         0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [-0.59356688, -0.33313909, -0.57766863,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [ 0.18349826,  0.04984713, -0.57766863,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [-1.32783714, -1.14506988, -0.57766863,  0.        ,  1.        ,
         0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.   

In [97]:
# now the data is ready let's build the model
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [98]:
models = {"support_vector_clf" : SVC(),
          "decison_tree_clf" : DecisionTreeClassifier(),
          "logistic_reg" : LogisticRegression(),
          "rf" : RandomForestClassifier()}

In [99]:
for i in range(len(models)):
  print(list(models.values())[i])

SVC()
DecisionTreeClassifier()
LogisticRegression()
RandomForestClassifier()


In [100]:
from sklearn.metrics import accuracy_score
def model_train_evaluate(X_train, X_test, y_train, y_test, models):
  evaluation = {}
  for i in range(len(models)):
    model = list(models.values())[i]
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    model_score = accuracy_score(y_test, y_pred)
    evaluation[list(models.keys())[i]] = model_score
  return evaluation

In [101]:
model_train_evaluate(X_train, X_test, y_train, y_test, models)

{'support_vector_clf': 0.9183673469387755,
 'decison_tree_clf': 0.9387755102040817,
 'logistic_reg': 0.9183673469387755,
 'rf': 0.8979591836734694}

In [102]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf

RandomForestClassifier()

In [103]:
X_train, X_test

(array([[-0.28611937, -1.47443803, -0.57766863, ...,  0.        ,
          1.        ,  0.        ],
        [ 0.02695905, -0.71612531,  1.47042924, ...,  0.        ,
          1.        ,  0.        ],
        [ 1.3716196 ,  1.19880579,  1.47042924, ...,  0.        ,
          1.        ,  0.        ],
        ...,
        [-0.23206267,  0.43283335, -0.57766863, ...,  0.        ,
          0.        ,  1.        ],
        [-1.06543688, -1.29060464, -0.57766863, ...,  1.        ,
          0.        ,  0.        ],
        [-0.29287646,  0.1034652 ,  0.44638031, ...,  1.        ,
          0.        ,  0.        ]]),
 array([[-1.85376383, -1.48209775, -1.60171757,  1.        ,  0.        ,
          0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
          0.        ],
        [-0.08453291,  0.04984713, -0.57766863,  1.        ,  0.        ,
          1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          1.        ],
        [ 0.79501474,  0.363895

In [104]:
# hyperparameter tuning
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
params = {'max_depth' : [1, 2, 3, 4, 5, 10, None],
          'n_estimators' : [30, 40, 50, 100, 200,300],
          'criterion' : ['gini', 'entropy']}

In [105]:
params

{'max_depth': [1, 2, 3, 4, 5, 10, None],
 'n_estimators': [30, 40, 50, 100, 200, 300],
 'criterion': ['gini', 'entropy']}

In [106]:
clf = RandomizedSearchCV(rf, param_distributions=params, cv = 5, verbose = 3, scoring = 'accuracy', n_iter = 10)

In [107]:
clf

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(),
                   param_distributions={'criterion': ['gini', 'entropy'],
                                        'max_depth': [1, 2, 3, 4, 5, 10, None],
                                        'n_estimators': [30, 40, 50, 100, 200,
                                                         300]},
                   scoring='accuracy', verbose=3)

In [108]:
clf.fit(X_train, y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV 1/5] END criterion=gini, max_depth=2, n_estimators=40;, score=0.923 total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=2, n_estimators=40;, score=0.974 total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=2, n_estimators=40;, score=1.000 total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=2, n_estimators=40;, score=1.000 total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=2, n_estimators=40;, score=1.000 total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=3, n_estimators=100;, score=0.923 total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=3, n_estimators=100;, score=0.974 total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=3, n_estimators=100;, score=1.000 total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=3, n_estimators=100;, score=1.000 total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=3, n_estimators=100;, score=1.000 total time=   0.3s
[CV 1/5] END criterion=e

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(),
                   param_distributions={'criterion': ['gini', 'entropy'],
                                        'max_depth': [1, 2, 3, 4, 5, 10, None],
                                        'n_estimators': [30, 40, 50, 100, 200,
                                                         300]},
                   scoring='accuracy', verbose=3)

In [109]:
clf.best_params_

{'n_estimators': 40, 'max_depth': 2, 'criterion': 'gini'}

In [110]:
clf.best_score_

np.float64(0.9794871794871796)

In [111]:
final_model = clf.best_estimator_

In [112]:
y_pred_final = final_model.predict(X_test)

In [113]:
y_pred_final

array([0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0])

In [114]:
accuracy_score(y_test, y_pred_final)

0.9183673469387755

In [116]:
# internel homework
# total_bill as target variable and make it a regressor problem
# automate fe, training, testing and also random forest regressor with MLR and SVR model