In [42]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [43]:
# adaboost classifier and regressor

In [44]:
# adaboost classifier

In [45]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [46]:
X, y = make_classification(n_samples=1000, n_features=20, n_classes=2, random_state = 1)

In [47]:
X

array([[-2.04582165, -0.13791624, -0.08071423, ...,  2.48194524,
         0.74236675,  0.23154789],
       [-0.98726024,  1.30120189,  2.37734888, ...,  0.55445754,
        -0.21892143, -0.37608578],
       [ 0.57335921,  0.09375582,  0.4662521 , ..., -0.6088508 ,
         0.79903499, -0.17121177],
       ...,
       [-0.70737159,  1.07650943,  0.58510456, ..., -1.51337602,
         0.90239871, -0.69230951],
       [-0.20706849,  1.17319848, -1.94478665, ..., -0.32820676,
         1.5711921 ,  1.14877729],
       [-2.16769231, -2.54871672,  2.89359255, ...,  0.71535366,
         0.34329241,  1.07350284]])

In [48]:
y

array([0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [49]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 1)

In [50]:
classifier = AdaBoostClassifier()
classifier

AdaBoostClassifier()

In [51]:
classifier.fit(X_train, y_train)

AdaBoostClassifier()

In [52]:
y_pred = classifier.predict(X_test)
y_pred

array([0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1])

In [53]:
print("Current model performance:")
print(f"Accuracy : {accuracy_score(y_test, y_pred)}")
print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Current model performance:
Accuracy : 0.8533333333333334
Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.86      0.84       139
           1       0.87      0.85      0.86       161

    accuracy                           0.85       300
   macro avg       0.85      0.85      0.85       300
weighted avg       0.85      0.85      0.85       300

Confusion Matrix:
[[119  20]
 [ 24 137]]


In [54]:
from sklearn.model_selection import GridSearchCV
param_gird = {
    'n_estimators' : [50, 100, 200],
    'learning_rate' : [0.01, 0.1, 1.0, 1.5, 2.0],
    'algorithm' : ['SAMME']
}

In [55]:
ada = AdaBoostClassifier()
clf = GridSearchCV(estimator=ada, param_grid=param_gird, cv = 5, verbose = 3)

In [56]:
clf

GridSearchCV(cv=5, estimator=AdaBoostClassifier(),
             param_grid={'algorithm': ['SAMME'],
                         'learning_rate': [0.01, 0.1, 1.0, 1.5, 2.0],
                         'n_estimators': [50, 100, 200]},
             verbose=3)

In [57]:
clf.fit(X_train, y_train)

Fitting 5 folds for each of 15 candidates, totalling 75 fits
[CV 1/5] END algorithm=SAMME, learning_rate=0.01, n_estimators=50;, score=0.857 total time=   0.2s
[CV 2/5] END algorithm=SAMME, learning_rate=0.01, n_estimators=50;, score=0.857 total time=   0.2s
[CV 3/5] END algorithm=SAMME, learning_rate=0.01, n_estimators=50;, score=0.857 total time=   0.2s
[CV 4/5] END algorithm=SAMME, learning_rate=0.01, n_estimators=50;, score=0.807 total time=   0.2s
[CV 5/5] END algorithm=SAMME, learning_rate=0.01, n_estimators=50;, score=0.821 total time=   0.3s
[CV 1/5] END algorithm=SAMME, learning_rate=0.01, n_estimators=100;, score=0.857 total time=   0.6s
[CV 2/5] END algorithm=SAMME, learning_rate=0.01, n_estimators=100;, score=0.857 total time=   0.6s
[CV 3/5] END algorithm=SAMME, learning_rate=0.01, n_estimators=100;, score=0.857 total time=   0.6s
[CV 4/5] END algorithm=SAMME, learning_rate=0.01, n_estimators=100;, score=0.807 total time=   0.6s
[CV 5/5] END algorithm=SAMME, learning_rate=

GridSearchCV(cv=5, estimator=AdaBoostClassifier(),
             param_grid={'algorithm': ['SAMME'],
                         'learning_rate': [0.01, 0.1, 1.0, 1.5, 2.0],
                         'n_estimators': [50, 100, 200]},
             verbose=3)

In [58]:
clf.best_params_

{'algorithm': 'SAMME', 'learning_rate': 0.1, 'n_estimators': 200}

In [59]:
clf.best_estimator_

AdaBoostClassifier(algorithm='SAMME', learning_rate=0.1, n_estimators=200)

In [60]:
best_model = clf.best_estimator_

In [61]:
y_pred = best_model.predict(X_test)

In [62]:
print("Current model performance:")
print(f"Accuracy : {accuracy_score(y_test, y_pred)}")
print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Current model performance:
Accuracy : 0.8566666666666667
Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.86      0.85       139
           1       0.88      0.85      0.86       161

    accuracy                           0.86       300
   macro avg       0.86      0.86      0.86       300
weighted avg       0.86      0.86      0.86       300

Confusion Matrix:
[[120  19]
 [ 24 137]]


In [63]:
# adaboost regression

In [64]:
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

In [65]:
X, y = make_regression(n_samples=1000, n_features=2, noise = 10, random_state = 1)

In [66]:
X

array([[-0.91542437, -1.94504696],
       [-2.30490794, -0.59246129],
       [-0.43750898, -0.78191168],
       ...,
       [-0.46867382,  0.02186284],
       [-0.44265541,  0.55753264],
       [-0.13971173,  0.85328219]])

In [67]:
y

array([-1.98367142e+02, -7.18777056e+01, -8.69703239e+01, -6.96492401e+01,
        1.82745760e+01, -3.77114686e+01,  3.92726728e+01, -9.78831863e+01,
       -9.79418533e+01, -1.18326213e+02,  7.37176065e+01,  1.15947984e+01,
       -1.14639116e+02,  1.18554758e+02, -1.09479268e+02,  4.55822523e+01,
        1.22163385e+01, -7.55247901e+01, -1.07584299e+02, -1.52546032e+02,
        6.76376929e+00,  9.63814831e+00, -2.16279129e+01,  7.04567440e+01,
        1.07700199e+02,  1.09477518e+01,  1.17165036e+02,  2.78449353e+01,
        3.24248766e+01, -1.55808165e+01,  9.64321593e+01, -2.68980403e+02,
        3.04398725e+01, -5.03731238e+01,  1.83865434e+01, -4.20020243e+01,
        2.60722898e+01, -4.24419694e+01, -2.84245422e+01,  7.87732991e+01,
        6.38527251e+01,  1.05600811e+02,  2.54784577e+01, -4.37001825e+01,
       -4.56639834e+01,  2.25475298e+01, -2.44159979e+01,  2.14189935e+00,
       -7.55772986e+01,  9.71903066e+01, -1.01696566e+02,  1.10063672e+02,
        3.74493102e+01,  

In [68]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 1)

In [69]:
regressor = AdaBoostRegressor()

In [70]:
regressor.fit(X_train, y_train)

AdaBoostRegressor()

In [71]:
y_pred = regressor.predict(X_test)

In [72]:
print("Current model performance:")
print(f"R2 score: {r2_score(y_test, y_pred)}")
print(f"Mean Absolute Error: {mean_absolute_error(y_test, y_pred)}")
print(f"Mean Squared Error: {mean_squared_error(y_test, y_pred)}")

Current model performance:
R2 score: 0.9527739532006315
Mean Absolute Error: 14.871087909898424
Mean Squared Error: 390.3457769405526


In [73]:
from sklearn.model_selection import GridSearchCV
param_gird = {
    'n_estimators' : [50, 100, 200],
    'learning_rate' : [0.01, 0.1, 0.5, 1.0, 1.5],
    'loss' : ['linear', 'square', 'exponential']
}

In [74]:
grid_search = GridSearchCV(estimator=regressor, param_grid=param_gird, cv = 5, verbose = 3)

In [75]:
grid_search

GridSearchCV(cv=5, estimator=AdaBoostRegressor(),
             param_grid={'learning_rate': [0.01, 0.1, 0.5, 1.0, 1.5],
                         'loss': ['linear', 'square', 'exponential'],
                         'n_estimators': [50, 100, 200]},
             verbose=3)

In [76]:
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 45 candidates, totalling 225 fits
[CV 1/5] END learning_rate=0.01, loss=linear, n_estimators=50;, score=0.936 total time=   0.3s
[CV 2/5] END learning_rate=0.01, loss=linear, n_estimators=50;, score=0.935 total time=   0.4s
[CV 3/5] END learning_rate=0.01, loss=linear, n_estimators=50;, score=0.953 total time=   0.3s
[CV 4/5] END learning_rate=0.01, loss=linear, n_estimators=50;, score=0.929 total time=   0.2s
[CV 5/5] END learning_rate=0.01, loss=linear, n_estimators=50;, score=0.938 total time=   0.3s
[CV 1/5] END learning_rate=0.01, loss=linear, n_estimators=100;, score=0.935 total time=   0.4s
[CV 2/5] END learning_rate=0.01, loss=linear, n_estimators=100;, score=0.937 total time=   0.4s
[CV 3/5] END learning_rate=0.01, loss=linear, n_estimators=100;, score=0.954 total time=   0.5s
[CV 4/5] END learning_rate=0.01, loss=linear, n_estimators=100;, score=0.932 total time=   0.4s
[CV 5/5] END learning_rate=0.01, loss=linear, n_estimators=100;, score=0.938 to

GridSearchCV(cv=5, estimator=AdaBoostRegressor(),
             param_grid={'learning_rate': [0.01, 0.1, 0.5, 1.0, 1.5],
                         'loss': ['linear', 'square', 'exponential'],
                         'n_estimators': [50, 100, 200]},
             verbose=3)

In [77]:
grid_search.best_params_

{'learning_rate': 1.5, 'loss': 'square', 'n_estimators': 200}

In [78]:
best = grid_search.best_estimator_

In [79]:
y_pred = best.predict(X_test)

In [80]:
print("Current model performance:")
print(f"R2 score: {r2_score(y_test, y_pred)}")
print(f"Mean Absolute Error: {mean_absolute_error(y_test, y_pred)}")
print(f"Mean Squared Error: {mean_squared_error(y_test, y_pred)}")

Current model performance:
R2 score: 0.9632222649003183
Mean Absolute Error: 13.065763734572448
Mean Squared Error: 303.9855028007779
